spring.application.name=TechCellShop

#JWT properties configuration
security.jwt.secret=9ZWHZKiD/Z79+Rp3/f0+wuueCo5e+vcOGTxNoAo1kriC2cA/N2jUyBcaDhWJb4Ky
security.jwt.expiration-ms=3600000

#RabbitMQ properties configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#Messaging properties configuration
app.messaging.order-created.exchange=techcellshop.order.exchange
app.messaging.order-created.routing-key=order.created
app.messaging.order-created.queue=techcellshop.order.created.q
app.messaging.order-created.dlq=techcellshop.order.created.dlq

app.messaging.order-created.dlx=techcellshop.order.exchange.dlx
app.messaging.order-created.dlq-routing-key=order.created.dlq

#Swagger properties configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
